config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  
  devise_for :users
  resources :users
  


  resources :cars
  resources :parkings
  get "homes/about"
  get '/about', to: 'homes#about'
  get '/contact', to: 'homes#contact'
  get '/info', to: 'users#instruction'
  # delete '/users/:id', to: 'users#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :parkings
  accepts_nested_attributes_for :parkings, reject_if: :all_blank, allow_destroy: true

  validates :brand, :model, :car_number, presence: true
  validates :colour, presence: true
 
end

app/models/parking.rb
class Parking < ApplicationRecord

  belongs_to :car
  belongs_to :user
  
  validates :maximum_size, :security_provision, :parking_duration, :chance_to_get_parking, :parking_cost_per_hour, :average_departure_time, :type_of_parking_facility, :type_of_security, :distance_to_supermarket, :distance_from_stores, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  paginates_per 4
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cars
  has_many :parkings

  validates :contact, presence: true, uniqueness: true
  validates :age, :name, :gender, :address, :department, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :age, :gender, :contact, :address, :department, :user_id])
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  before_action :set_car, only: %i[show edit destroy update]

  def index
    @q = current_user.cars.ransack(params[:q])
    @cars = @q.result(distinct: true).page(params[:page])
  end

  def show
  end

  def new
    @car = Car.new(user_id: params[:user_id])
  end

  def create
    @car = Car.new(car_params)

    if @car.save
      redirect_to @car
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to @car
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @car.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def car_params
    params.require(:car).permit(:brand, :model, :colour, :car_number, :car_owner, :user_id)
  end

  def set_car
    @car = Car.find(params[:id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  def index
    @parkings = Parking.all
  end

  def show
    # @parking = current_user.cars.parking
    @parking = Parking.find(params[:id])
  end

  def new
    @parking = current_user.parkings.new(car_id: params[:car_id])
  end
  
  def create
    @parking = Parking.new(parking_params)
    if @parking.save
      UserMailer.welcome_email(current_user.id).deliver_now
      redirect_to @parking
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def destroy
    @parking = Parking.find(params[:id])
    @parking.destroy

    redirect_to cars_path, status: :see_other
  end
  
  private
    def parking_params
      params.require(:parking).permit(:maximum_size, :security_provision, :parking_duration, :chance_to_get_parking, :parking_cost_per_hour, :average_departure_time, :type_of_parking_facility, :type_of_security, :distance_to_supermarket, :distance_from_stores, :car_id, :user_id, :parking_name)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def user_params
      params.require(:user).permit(:name, :username, :age, :gender, :contact, :address, :department)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/_form.html.erb
<%= form_with model: car do |form| %>
  
  <p>
    <%= form.select :user_id, ['1', '2', '3'] %>
  </p>
  <p>
    <%= form.label :brand %><br>
    <%= form.text_field :brand %>
  </p>
  <p>
    <%= form.label :model %><br>
    <%= form.text_field :model %>
  </p>
  <p>
    <%= form.label :colour %><br>
    <%= form.text_field :colour %>
  </p>
  <p>
    <%= form.label :car_number %><br>
    <%= form.text_field :car_number %>
  </p>
  <p>
    <%= form.label :Owner %><br>
    <%= form.select :car_owner, ['self', 'onrent', 'other'] %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
<br>
<%= link_to 'Back to Car', cars_path %>
</div>

app/views/cars/edit.html.erb
<h2>change car info</h2>

<%= render 'form', car: @car %>

app/views/cars/index.html.erb
<%= search_form_for @q do |f| %>

  <%= f.label :Model_cont %>
  <%= f.search_field :model_cont, placeholder: "search car" %>

  <%= f.submit %>
<% end %>
<% @cars.each do |car| %>
<ul>
  <li><%=car.brand%>
    <%= link_to car.model, car_path(car.user_id) %>
  </li>
</ul>
<% end %>
<h5><%= link_to 'Add New Car', new_car_path(user_id: params[:user_id]) %></h5>

app/views/cars/new.html.erb
<h2>New Car</h2>

<%= render 'form', car: @car %>

app/views/cars/show.html.erb
<div> 
  <h2>Here is your complete information about car</h2>
  <table border="collaspe" cellpadding="8">
    <thead>
      <th>Car index number</th>
      <th>Brand</th>
      <th>Model </th>
      <th>Colour </th>
      <th>Car No. </th>
      <th>Owner</th>
    </thead>
    <tbody>
      <td><%= @car.id %></td>
      <td><%= @car.brand %></td>
      <td><%= @car.model %></td>
      <td><%= @car.colour %></td>
      <td><%= @car.car_number %></td>
      <td><%= @car.car_owner %></td>
    </tbody>
  </table>
</div>
<ul>
    <li><%= link_to "Edit Current Car", edit_car_path(@car) %></li><br>
    <li><%= link_to "All Cars", cars_path %></li><br>
    <li><%= link_to "New Car", new_car_path %></li><br>
    <li><%= link_to "Remove car from this app", car_path(@car), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>
<h4><%= link_to 'book parking', new_parking_path(@car.id) %></h4>
<div>
  <%= link_to 'parking history', parkings_path %>
</div>

app/views/homes/about.html.erb
<h2>About our website</h2>

<p> This is a parking website in which <br>we can register user and add there cars <br>

And the main purpose of this aopplication is to<br> book parking slot for registered cars</p>

app/views/homes/contact.html.erb
<h2>Contact Us</h2>

<h4>This article is for helping you </h4>
<p> This application gives the best experience of parkings <br>slot for their user so they have <br>a pefect and best parking for their imported cars<br> because every car's is giving the feel of being king<br> of their user so here is your kingdom saver website</p><br>

<p> We want you give the best we have</p>


<ul>
  <li>Our email :- <br>
  parking@text.com</li>
  <li>Our Insta page<br>
  Parking_akash</li>
  <li>Our contact :- <br>
  011 2553 2553 </li>
  <li>permanent address:- <br>Sukhliya Indore, Madhya Pradesh</li>
</ul>

app/views/homes/index.html.erb
<div class="bg-home">
  <img src="<%= asset_path("honda.jpg")%>" width="100%", height="calc(100vh - 56px)">
  <h1>Welcome to our parking application</h1>
  <!-- <h3><button class="btn btn-outline-success" ><%#= link_to 'view all user', users_path, class: "btn btn-warning" %></button></h3>  -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body background-img="" style="background-color: gainsboro;">
    <nav class="navbar navbar-expand-lg bg-Gold ">
      <div class="container-fluid">
      <a class="navbar-brand" href="/info">
        <img src="https://freepngimg.com/thumb/car/6-2-car-png-file.png" width="50" height="40">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/users">All Users</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/about">About us</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="/contact">Contact us</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="/admin/admin_users">Check admin</a>
          </li>
     
          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="true">
              Dropdown
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          -->
          <li class="nav-item">
        </ul> 
          <% if user_signed_in? %>
            <%= current_user.email %>
            <%#= link_to 'Logout', destroy_admin_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>          <!-- <%#= button_to 'Sign Out', destroy_user_session_path, method: :delete,
              form: {data: {turbo_confirm: 'Are you sure?'}} %> -->
            <%= link_to "Sign out", destroy_user_session_path, method: :delete %> 
          <% else %>
            <li class="nav-item">
              <button class="btn btn-outline-success" type="submit">
              <%= link_to 'create user', new_user_registration_path %></button>
              <button class="btn btn-outline-success" type="submit">
              <%= link_to 'log in user', new_user_session_path %></button>
            </li>
          <% end %>
      </div>
    </div>
  </nav>
    <center>
      <%= yield %>
    </center>
  </body>
</html>

app/views/parkings/_form.html.erb
<%= simple_form_for parking do |form| %>
  
  <p>
    <%= form.label :car_index_number %><br>
    <%= form.text_field :car_id %>
  </p>

  <p>
    <%= form.hidden_field :user_id %>
  </p>

  <p>
    <%= form.label :security_provision %><br>
    <%= form.text_field :security_provision %>
  </p>

  <p>
    <%= form.label :parking_duration %><br>
    <%= form.text_field :parking_duration %>
  </p>

  <p>
    <%= form.label :chance_to_get_parking %><br>
    <%= form.select :chance_to_get_parking,['75%'] %>
  </p>
  
  <p>
    <%= form.label :average_departure_time %><br>
    <%= form.text_field :average_departure_time %>
  </p>
  
  <p>
    <%= form.label :parking_cost_per_hour %><br>
    <%= form.select :parking_cost_per_hour, ['50 rupees per hour', '100 rupees per hour', '400 rupees per hour'] %>
  </p>
  
  <p>
    <%= form.label :maximum_size %><br>
    <%= form.select :maximum_size, ['40 parking spaces'] %>
  </p>
  
  <p>
    <%= form.label :parking_name %><br>
    <%= form.select :parking_name, ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8", "D9", "D10"] %>
  </p>
  
  <p>
    <%= form.label :type_of_parking_facility %><br>
    <%= form.select :type_of_parking_facility, ['angel parking', 'perpendicular parking', 'parallel parking', 'lot parking', 'bay parking', 'others'] %>
  </p>
  
  <p>
    <%= form.label :type_of_security %><br>
    <%= form.select :type_of_security, ['cctv', 'security guard', 'emergency panel', 'fire proof', 'others'] %>
  </p>
  
  <p>
    <%= form.label :distance_to_supermarket %><br>
    <%= form.select :distance_to_supermarket, ['100 meter', '200 meter', '500 meter', '1 km'] %>
  </p>
  
  <p>
    <%= form.label :distance_from_stores %><br>
    <%= form.select :distance_from_stores, ['100 meter', '200 meter', '500 meter', '1 km'] %>
  </p>
  
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/parkings/index.html.erb
<h2>Your parking history</h2>
<% @parkings.each do |p| %>
  <ul>
    <li>parked By the user whose user id is <%= p.user_id %> and the date and time of car parking is <%= p.created_at %>and booked the parking for <%= p.parking_duration %></li>
  </ul>
<%end%>
  <%= link_to "back", :back %>

app/views/parkings/new.html.erb
<h2>Book a new parking here :- </h2>
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
<%=render "form", parking: @parking %>

app/views/parkings/show.html.erb
  <div> 
  <h2>Hello <%= current_user.name %> Here is your complete information of booking</h2>
  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  <table border="collaspe" cellpadding="8">
    <thead>
      <th>Name</th>
      <th>email </th>
    </thead>
    <tbody>
      <td><%= current_user.name %></td>
      <td><%= current_user.email %></td>
    </tbody>
  </table><br>
  <table border="collaspe" cellpadding="8">
    <thead>
      <th>Brand</th>
      <th>Model </th>
      <th>Colour </th>
      <th>Car No. </th>
      <th>Owner</th>
    </thead>
    <tbody>
      <% current_user.cars.each do |car| %>
      <td><%= car.brand %></td>
      <td><%= car.model %></td >
      <td><%= car.colour %></td>
      <td><%= car.car_number %></td>
      <td><%= car.car_owner %></td>
      <% end %>
    </tbody></table><br>
      <div>You got succesfully <%= @parking.parking_name %> place </div>
    <table border="collaspe" cellpadding="8">
    <thead>
      <th>security_provision</th>
      <th>maximum_size </th>
      <th>parking_duration </th>
      <th>chance_to_get_parking</th>
      <th>parking_cost_per_hour</th><br>
    </thead>
    <tbody>
      <td><%= @parking.security_provision%></td>
      <td><%= @parking.maximum_size %></td >
      <td><%= @parking.parking_duration %></td>
      <td><%= @parking.chance_to_get_parking %></td>
      <td><%= @parking.parking_cost_per_hour %></td><br>
    </tbody>
  </table>
  <table border="collaspe" cellpadding="8">
    <thead>
      <th>average_departure_time</th>
      <th>type_of_parking_facility </th>
      <th>type_of_security </th>
      <th>distance_to_supermarket</th>
      <th>distance_from_stores</th>
    </thead>
    <tbody>
      <td><%= @parking.average_departure_time %></td>
      <td><%= @parking.type_of_parking_facility%></td>
      <td><%= @parking.type_of_security %></td >
      <td><%= @parking.distance_to_supermarket %></td>
      <td><%= @parking.distance_from_stores %></td>
    </tbody>
  </table>
</div>

<h4><li><%= link_to "Remove Booking", :back %></li></h4><br>
<h4><%= link_to 'back to users', root_path %></h4>

app/views/users/index.html.erb
<%= search_form_for @q do |f| %>

  <%= f.label :name_cont %>
  <%= f.search_field :name_cont, placeholder: "search user" %>

  <%= f.submit %>
<% end %>
<br>
  <% @users.each do |user| %>
    <li>
      <h4><%= link_to user.name, user %></h4>
    </li>
    <% end %><br><br><br>
   <button style="border-inline-start-color: yellow;"><a class="nav-link active" aria-current="page" href="/">Back</a></button><br>

<%= paginate @users %>

app/views/users/instruction.html.erb
<h3><ol>
  <li> first create your own user .</li>
  <li> now you are able to add cars ,update user information , or log out your own contact</li>
  <li> then next go to you cars by clicking on car button shown in bottom </li>
  <li> then add your car </li>
  <li> after that book parking</li>
</ol></h3> 


<h2>Follow these steps to book your parking :-</h2>

app/views/users/show.html.erb
<div> 
<h2>Here is your complete information </h2>
  <table border="collaspe" cellpadding="8">
    <thead>
      <th>Username</th>
      <th>Name</th>
      <th>Age </th>
      <th>Gender </th>
      <th>Contact </th>
      <th>Address</th>
      <th>Department</th>
    </thead>
    <tbody>
      <td><%= @user.username %></td>
      <td><%= @user.name %></td>
      <td><%= @user.age %></td>
      <td><%= @user.gender %></td>
      <td><%= @user.contact %></td>
      <td><%= @user.address %></td>
      <td><%= @user.department %></td>
    </tbody>
  </table>
</div>

<ul>
  <li><%= link_to "Back to Users", users_path %></li><br>
    <li><%= link_to "Edit Current User", edit_user_registration_path(@user) %></li><br>
  <li><%= link_to "Cars", cars_path(@user.id) %></li>
</ul>